#
filters:
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/environment-banner/environment-banner.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/environment-banner/environment-banner.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/home/home.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/home/home.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/layout/layout.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/layout/layout.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/material/material.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/material/material.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/password-recovery/password-recovery.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/password-recovery/password-recovery.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/profile/profile.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/profile/profile.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/search/search.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/search/search.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/signin/signin.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/signin/signin.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/shared/shared.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/shared/shared.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/register/register.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/register/register.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/institutional/institutional.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/institutional/institutional.<lang>.properties
  #
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/inbox/inbox.en.properties
    translation_files_expression: src/locale/properties/inbox/inbox.<lang>.properties
  #
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/delegators/delegators.en.properties
    translation_files_expression: src/locale/properties/delegators/delegators.<lang>.properties
  #
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/authorize/authorize.en.properties
    translation_files_expression: src/locale/properties/authorize/authorize.<lang>.properties
  #
  - filter_type: file
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/linking/linking.en.properties
    translation_files_expression: src/locale/properties/linking/linking.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/two-factor/two-factor.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/two-factor/two-factor.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/record/record.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/record/record.<lang>.properties

  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/top-bar/top-bar.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/top-bar/top-bar.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/peer-review/peer-review.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/peer-review/peer-review.<lang>.properties
  #
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/my-orcid-alerts/my-orcid-alerts.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/my-orcid-alerts/my-orcid-alerts.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/research-resources/research-resources.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/research-resources/research-resources.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/funding/funding.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/funding/funding.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/works/works.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/works/works.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/side-bar/side-bar.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/side-bar/side-bar.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/account/account.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/account/account.<lang>.properties

  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: UNICODEPROPERTIES
    source_language: en
    source_file: src/locale/properties/interstitials/interstitials.en.properties
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: src/locale/properties/interstitials/interstitials.<lang>.properties
