on:
  push:
    branches:
      - main
      - development
  pull_request:

name: Code formatting and testing languages‚úçÔ∏è

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn format
      - run: yarn build:i18n:generate-testing
      - uses: EndBug/add-and-commit@v4
        with:
          message: 'ü§ñ GITHUB ACTIONS'
        env:
          GITHUB_TOKEN: ${{ secrets.ORCID_MACHINE }}
