on:
  push:
    branches:
      - main
      - development
  pull_request:

name: Code formatting and testing languagesâœï¸

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn format
      - run: yarn build:i18n:generate-testing
      - name: Commit languages files changes
        uses: EndBug/add-and-commit@v4
        with:
          message: 'ğŸ¤– GITHUB ACTIONS: testing languages ğŸ¤–'
        env:
          GITHUB_TOKEN: ${{ secrets.ORCID_MACHINE }}
