on: [push, pull_request]
name: Test Build Production ğŸ› ï¸

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: 'v16.13.2'
  - run: yarn
  - run: yarn build:prod
